fx_version 'cerulean'
game 'gta5'

author '919DESIGN & Envi-Scripts'
description 'StreetKings txAdmin Recipe'
version '1.1.0'

dependencies {
    'oxmysql',
    'ox_lib',
    'streetkings_audio'
}

client_scripts {
    'modules/core/locales_c.lua',
    'modules/environment/environment_c.lua',
    'modules/notify/notify_c.lua',
    'modules/soundtrack/soundtrack_c.lua',
    'modules/core/game_state_c.lua',
    'modules/core/sk_helpers_c.lua',
    'modules/core/input_c.lua',
    'modules/core/cinematic_camera_block_c.lua',
    'modules/controllerfriendly/controllerfriendly_c.lua',
    'modules/core/vehicle_lock_c.lua',
    'modules/core/door_lock_c.lua',
    'modules/core/custom_plates.lua',
    'modules/waypoints/waypoints_c.lua',
    'modules/avatar/avatar_c.lua',
    'modules/avatar/avatar_stores_c.lua',
    'modules/main_menu/main_menu_camera_c.lua',
    'modules/main_menu/main_menu_flow_c.lua',
    'modules/main_menu/main_menu_nui_c.lua',
    'modules/main_menu/main_menu_c.lua',
    'modules/initiation/initiation_c.lua',
    'modules/initiation/initiation_nui_c.lua',
    'modules/tutorial/tutorial_c.lua',
    'modules/speedometer/speedometer_c.lua',
    'modules/progression/progression_c.lua',
    'modules/freeroam/police_c.lua',
    'modules/freeroam/camera_c.lua',
    'modules/freeroam/speed_cameras_c.lua',
    'modules/freeroam/npc_challenge_c.lua',
    'modules/property/property_c.lua',
    'modules/property/property_invite_c.lua',
    'modules/nametags/nametags_c.lua',
    'modules/freeroam/freeroam_c.lua',
    'modules/stunts/stunt_jump_c.lua',
    'modules/devtools/stunt_devtool_c.lua',
    'modules/gearbox/gearbox_c.lua',
    'modules/nitrous/nitrous_c.lua',
    'modules/events/rampage_c.lua',
    'modules/events/event_preview_c.lua',
    'modules/events/events_freeroam_markers_c.lua',
    'modules/events/events_rampage_markers_c.lua',
    'modules/events/events_chooser_c.lua',
    'modules/events/events_multiplayer_c.lua',
    'modules/events/events_c.lua',
    'modules/devtools/race_editor_freecam_c.lua',
    'modules/devtools/race_devtool_c.lua',
    'modules/repair/repair_c.lua',
    'modules/shop/shop_c.lua',
    'modules/garage/garage_c.lua',
    'modules/dealership/dealership_c.lua',
    'modules/missions/cutscene_c.lua',
    'data/cutscenes/chapter1_cutscenes_c.lua',
    'modules/missions/tailing_c.lua',
    'modules/missions/objectives/_npc_handoff_c.lua',
    'modules/missions/objectives/visit_location_c.lua',
    'modules/missions/objectives/complete_event_c.lua',
    'modules/missions/objectives/pickup_package_c.lua',
    'modules/missions/objectives/deliver_package_c.lua',
    'modules/missions/objectives/dialog_c.lua',
    'modules/missions/objectives/escape_c.lua',
    'modules/missions/objectives/tail_npc_c.lua',
    'modules/missions/objectives/npc_challenge_c.lua',
    'modules/missions/objectives/scripted_race_c.lua',
    'modules/missions/objectives/getaway_pickup_c.lua',
    'modules/missions/objectives/getaway_ride_c.lua',
    'modules/missions/objectives/finale_arrest_c.lua',
    'modules/missions/objectives/stop_vehicle_c.lua',
    'modules/missions/car_meet_c.lua',
    'modules/missions/missions_c.lua',
    'modules/phone/phone_c.lua',
    'modules/phone/tablet_customization_c.lua',
    'modules/phone/phone_sdk_c.lua',
    'modules/phone/profile_app_c.lua',
    'modules/phone/towing_c.lua',
    'modules/phone/map_c.lua',
    'modules/settings/settings_c.lua',
    'modules/stats/stats_c.lua',
    'modules/leaderboard/leaderboard_c.lua',
    'modules/messages/messages_c.lua',
    'modules/init/init_c.lua',
    'modules/core/warp_c.lua',
    'modules/admincommands/admincommands_c.lua',
    'modules/pausemenu/pausemenu_c.lua',
    'modules/hangoutzones/hangoutzones_c.lua',
    'modules/adminbridge/garage_admin_refresh_c.lua',
}

server_scripts {
    '@oxmysql/lib/MySQL.lua',
    'modules/waypoints/waypoints_s.lua',
    'modules/environment/environment_s.lua',
    'modules/core/game_state_s.lua',
    'modules/storage/saves_s.lua',
    'modules/avatar/avatar_s.lua',
    'modules/progression/progression_s.lua',
    'modules/initiation/initiation_s.lua',
    'modules/freeroam/freeroam_s.lua',
    'modules/nametags/nametags_s.lua',
    'modules/freeroam/npc_challenge_s.lua',
    'modules/freeroam/police_s.lua',
    'modules/property/property_s.lua',
    'modules/property/property_invite_s.lua',
    'modules/shop/shop_s.lua',
    'modules/garage/garage_s.lua',
    'modules/speedometer/speedometer_s.lua',
    'modules/dealership/dealership_s.lua',
    'modules/admincommands/admincommands_s.lua',
    'modules/pausemenu/pausemenu_s.lua',
    'modules/settings/settings_s.lua',
    'modules/stats/stats_s.lua',
    'modules/phone/tablet_customization_s.lua',
    'modules/phone/phone_sdk_s.lua',
    'modules/phone/profile_app_s.lua',
    'modules/messages/message_defs.lua',
    'modules/messages/messages_s.lua',
    'modules/events/events_state_s.lua',
    'modules/events/events_db_s.lua',
    'modules/events/events_query_s.lua',
    'modules/events/events_rewards_s.lua',
    'modules/events/events_daily_s.lua',
    'modules/events/events_validation_s.lua',
    'modules/events/events_exevent_validation_s.lua',
    'modules/events/events_submit_s.lua',
    'modules/events/events_leaderboard_s.lua',
    'modules/events/events_lobby_s.lua',
    'modules/events/events_multiplayer_s.lua',
    'modules/events/events_handlers_s.lua',
    'modules/stunts/stunt_jump_s.lua',
    'modules/tutorial/tutorial_s.lua',
    'modules/missions/mission_defs.lua',
    'modules/missions/missions_s.lua',
    'modules/missions/car_meet_s.lua',
    'modules/hangoutzones/hangoutzones_s.lua',
}

shared_scripts {
    '@ox_lib/init.lua',
    'data/sk_config.lua',
    'locales/en.lua',
    'locales/es.lua',
    'modules/core/locales_sh.lua',
    'data/repair_stations.lua',
    'data/waypoints_config.lua',
    'shared/vehicles.lua',
    'data/environment.lua',
    'data/game_vehicles.lua',
    'data/events_config.lua',
    'data/garage.lua',
    'data/dealership.lua',
    'modules/core/game_state_sh.lua',
    'data/shop.lua',
    'data/property.lua',
    'data/avatar_shop.lua',
    'data/progression.lua',
    'modules/core/vehicle_plate_sh.lua',
    'modules/storage/save_sh.lua',
    'modules/property/property_sh.lua',
    'modules/avatar/avatar_sh.lua',
    'modules/progression/progression_sh.lua',
    'modules/shop/shop_sh.lua',
    'modules/events/event_defs_sh.lua',
    'modules/events/event_route_sh.lua',
    'data/events.lua',
    'data/speed_cameras.lua',
    'data/police_traps.lua',
    'data/stunt_jumps.lua',
    'data/tutorial_config.lua',
    'modules/missions/missions_sh.lua',
    'data/missions.lua',
    'data/hangout_zones.lua',
}

ui_page 'html/index.html'

loadscreen 'html/loadscreen.html'
loadscreen_cursor 'no'
loadscreen_manual_shutdown 'yes'

files {
    'html/**/*',
    'customplates/*.png',
    'modules/soundtrack/soundtrack.dat',
    'modules/soundtrack/soundtrack_garage.dat',
    'modules/soundtrack/staticemitters.json'
}
